#!/usr/bin/env bash
# Displays `To infinity and beyond` indefinitely
#+In between each iteration of the loop, add `sleep 2`
# Displays `I am invincible` when receiving `SIGTERM` signal

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done 
