#!/usr/bin/env bash
# Display numbers 1 to 100 in a list format
# When number is a multiple of 3 and 5:
#+Displays "FizzBuzz"
# When number is multiple of  3:
#+Displays "Fizz"
# When number is multiple of 5:
#+Displays "Buzz"

for (( i = 1; i <= 100; i++  ))
do
	if (( "$i" % 3 == 0 )) && (( "$i" % 5 == 0 )); then
		echo "FizzBuzz"
	elif (( "$i" % 3 == 0 )); then
		echo "Fizz"
	elif (( "$i" % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
