#!/usr/bin/env bash
# Tells a story based on the contents of
#+the `/etc/passwd` file

file="/etc/passwd"
f1=""
f2=""
f3=""

while IFS=: read -r user
do
	f1="$(echo "$user" | cut -d":" -f1)"
	f2="$(echo "$user" | cut -d":" -f4)"
	f3="$(echo "$user" | cut -d":" -f6)"
	f4="$(echo "$user" | cut -d":" -f7)"
	f5="$(echo "$user" | cut -d":" -f3)"
	f6="$(echo "$user" | cut -d":" -f2)"
	f7="$(echo "$user" | cut -d":" -f5)"
	
	echo "The user ${f1} is part of the ${f2} gang, lives in ${f3} and rides ${f4}. ${f5}'s place is protected by the passcode ${f6}, more info about the user here: ${f7}"
done < "$file"
