#!/usr/bin/env bash
# Parses Apache log files in list format
# Groups visitors by IP & HTTP status code
# Displays the number of occurrences, IP
#+and HTTP status code of each log,
#+in sorted order

log="apache-access.log"
awk -F ' ' '{print $1, $9}' $log | sort | uniq -c | sort -nr
