#!/usr/bin/env bash
# Displays "Best School" 10 times but
#+for the 9th iteration, displays
#+"Best School" and "Hi" on a new line

n=0
while (( "$n" != 10 ))
do
	if [[ "$n" == 8 ]]
	then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	((n++))
done
