#!/usr/bin/env bash
# Loops from 1 to 10 and displays different
#+strings depending on the number of loops

n=0
while (( "$n" != 10 ))
do
	if [[ "$n" -eq 3 ]]
	then
		echo "bad luck"
	elif [[ "$n" -eq 7 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
