#!/usr/bin/env bash
# Display numbers from 1 to 20 and also
#+certain strings base on specific numbers

n=1
while (( "$n" <= 20 ))
do
	case "$n" in
		4)
			echo -e "$n\nbad luck from China"
			;;
		9)
			echo -e "$n\nbad luck from Japan"
			;;
		17)
			echo -e "$n\nbad luck from Italy"
			;;
		*)
			echo "$n"
			;;
	esac
	((n++))
done
